---

- hosts: flask
  become: true
  gather_facts: no
  tasks:
    - name: Copy docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: docker-compose.yml
    - name: Docker stop
      shell: docker-compose stop {{ registry_admin }}    

    - name: Make deploy
      shell: docker-compose up -d {{ registry_admin }}

    - name: Remove docker-compose.yml
      file: path=docker-compose.yml state=absent

...
