---

- hosts: sentry
  become: true
  gather_facts: no
  tasks:
    - name: Copy files
      synchronize:
        src: files/
        dest: /home/{{ ansible_user }}/{{ project_name }} 

    - name: Copy Dockerfile template
      template:
        src: templates/Dockerfile.j2
        dest: /home/{{ ansible_user }}/{{ project_name }}/sentry/Dockerfile

    - name: Copy install script template
      template:
        src: templates/install.sh.j2
        dest: /home/{{ ansible_user }}/{{ project_name }}/install.sh
        mode: +x        

    - name: Make deploy
      shell: /home/{{ ansible_user }}/{{ project_name }}/install.sh 

    - name: Create sentry user
      shell: docker-compose run -f /home/{{ ansible_user }}/{{ project_name }} --rm web createuser --superuser --email '{{ sentry_user_email }}' --password '{{ sentry_user_password }}'
      ignore_errors: yes

    - name: Up all containers
      shell: docker-compose -f /home/{{ ansible_user }}/{{ project_name }}/docker-compose.yml up -d
    
    - name: Make migration
      shell: docker exec -t {{ project_name }}_web_1 sentry upgrade

    - name: Delete deploy files
      file: 
        path: /home/'{{ ansible_user }}'/'{{ project_name }}'
        state: absent

...
